---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    user: '{{ user }}'
    pwd: '{{ pwd }}'
  tasks:
  - name: Check if the user exists
    shell: id -u '{{ user }}'
    register: user_exists
    ignore_errors: true

  - name: Update password user sa
    user:
      name: '{{ user }}'
      password: '{{ pwd | password_hash("sha512") }}'
      update_password: always
    when: user_exists.rc == 0

  - debug:
      msg: User already exists
    when: user_exists.rc != 0
